version: "2"

run:
  timeout: 5m
  tests: true

output:
  formats:
    - colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocyclo:
      min-complexity: 15
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    misspell:
      locale: US
    lll:
      line-length: 120
    funlen:
      lines: 100
      statements: 50
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - gocyclo
    - misspell
    - unparam
    - goconst
    - prealloc
    - copyloopvar
    - gocritic
    - bodyclose
    - dogsled
    - dupl
    - errname
    - errorlint
    - exhaustive
    - funlen
    - gochecknoinits
    - gocognit
    - gosec
    - lll
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - typecheck
    - unconvert
    - whitespace
  exclusions:
    paths:
      - vendor
      - bin
      - dist
    rules:
    - path: ".*\\.pb\\.go$"
      linters:
        - all
    - path: ".*_gen\\.go$"
      linters:
        - all
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - funlen
        - gocyclo
        - goconst
        - unparam
        - gocognit
        - lll
        - errorlint
    - path: internal/version
      text: "version"
    - linters:
        - lll
      source: "^//go:generate "
    # Exclude duplicate code warnings (dupl) - these are intentional patterns
    - linters:
        - dupl
      path: ".*"
    # Exclude complexity warnings for examples
    - path: internal/storage/examples\.go
      linters:
        - gocyclo
        - funlen
        - gocognit
    # Exclude line length warnings - many are due to long gRPC function signatures
    - linters:
        - lll
      path: ".*"
    # Exclude unused parameter warnings for error mapping functions
    - linters:
        - unparam
      text: "unused.*(resourcePath|schemaID|resource)"
