run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - bin
    - dist
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120
  funlen:
    lines: 100
    statements: 50
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - gocyclo
    - misspell
    - unparam
    - goconst
    - prealloc
    - copyloopvar
    - gocritic
    - bodyclose
    - dogsled
    - dupl
    - errname
    - errorlint
    - exhaustive
    - funlen
    - gochecknoinits
    - gocognit
    - gosec
    - lll
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - typecheck
    - unconvert
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - funlen
        - gocyclo
    - path: internal/version
      text: "version"
    - linters:
        - lll
      source: "^//go:generate "

